### ISSUE TITLE
Which specific smart card that supported this Applet?

### ISSUE THREAD

**Issue by fightyz** [LedgerHQ/ledger-u2f-javacard#1]
As I am a developer in China where many smart card vendors still just support JavaCard 2.2, there is a  few choices for me to buy the smart card. So, can you tell me which smart card you deployed on?

Regards

Yang Zhou
Postgraduate Student
University of Electronic Science and Technology of China

**Comment by btchip** [comment]
Hi 

We deployed on a 2.4.2 JCOP. This application needs Elliptic Curve support, which is available in Java Card Classic 3.0.1
